### ISSUE TITLE
Thiết kế giao diện

### ISSUE THREAD

**Issue by Jing-Shuai** [Nhom24FrontEnd/ProjectProntEnd#2]
1.Nguyễn Công Vũ -Giỏ hàng
2.Đào Xuân Đức - Danh sách sản phẩm          
Bùi Đoàn Anh Duy-Chi tiết 1 sản phẩm
Thiết kế luôn các màn hình phát sinh
![Screenshot (279)](https://user-images.githubusercontent.com/73984444/119253457-85aef600-bbdb-11eb-9a6c-2fa543ae831f.png)
Decline  21h00 Ngày 25/05/2021

**Comment by Jing-Shuai** [comment]
[Uploading Shopsachtrangchugiohang.docx…]()

**Comment by Jing-Shuai** [comment]
[Shopsachtrangchugiohang.docx](https://github.com/Nhom24FrontEnd/ProjectProntEnd/files/6551852/Shopsachtrangchugiohang.docx)

**Comment by Niss1407** [comment]
![Capture](https://user-images.githubusercontent.com/83705299/119994254-9fdf3e80-bff6-11eb-9095-ca3472a45ab4.PNG)

**Comment by DuyBuii** [comment]
![Uploading image.png…]()

**Comment by DuyBuii** [comment]
![a](https://user-images.githubusercontent.com/73979921/120005878-82b06d00-c002-11eb-825c-57d13dee1dd1.png)

**Comment by DuyBuii** [comment]
![image](https://user-images.githubusercontent.com/73979921/120005929-94921000-c002-11eb-91df-54f40e5f1d31.png)

**Comment by DuyBuii** [comment]
![image](https://user-images.githubusercontent.com/73979921/120058209-88926680-c073-11eb-9a5f-7b7e6415574b.png)
